# Generated by Django 4.0.4 on 2022-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stavki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
