# Generated by Django 4.0.4 on 2022-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stavki', '0002_alter_users_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='winner',
            field=models.CharField(choices=[(1, models.CharField(max_length=255)), (0, models.CharField(max_length=255))], default=None, max_length=300),
        ),
    ]
